import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';

const MONTH_NAMES = [
  '',
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export interface BillPdfData {
  billNumber: string;
  billDate: string | Date;
  billingMonth?: number | null;
  billingYear?: number | null;
  schoolName: string;
  schoolCode: string;
  schoolEmail?: string | null;
  schoolPhone?: string | null;
  schoolAddress?: string | null;
  studentCount?: number;
  pricePerStudent?: number;
  description?: string | null;
  amount: number;
  tax: number;
  totalAmount: number;
  status: string;
  createdByName?: string | null;
  approvedByName?: string | null;
  approvedAt?: string | Date | null;
}

@Injectable()
export class BillPdfService {
  private readonly logger = new Logger(BillPdfService.name);

  /**
   * Generates a clean, professional invoice PDF buffer matching the Brainros invoice requirements.
   */
  async generateBillPdf(data: BillPdfData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 40,
          info: {
            Title: `Invoice - ${data.billNumber}`,
            Author: 'Brainros Exam Management Platform',
          },
        });

        const buffers: Buffer[] = [];
        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err) => reject(err));

        const formattedDate = new Date(data.billDate).toLocaleDateString('en-IN', {
          day: '2-digit',
          month: 'short',
          year: 'numeric',
        });

        const billingPeriodStr =
          data.billingMonth && data.billingYear
            ? `${MONTH_NAMES[data.billingMonth] || 'Month ' + data.billingMonth} ${data.billingYear}`
            : 'Custom Period';

        const studentCount = data.studentCount ?? 0;
        const pricePerStudent = data.pricePerStudent ?? 300;

        // ── 1. HEADER & BRANDING ──────────────────────────────────
        doc.rect(40, 40, 515, 65).fill('#0f172a');

        doc.fillColor('#ffffff')
          .fontSize(24)
          .font('Helvetica-Bold')
          .text('BRAINROS', 55, 52);

        doc.fillColor('#94a3b8')
          .fontSize(10)
          .font('Helvetica')
          .text('Exam Management & Academic Assessment Platform', 55, 80);

        doc.fillColor('#38bdf8')
          .fontSize(18)
          .font('Helvetica-Bold')
          .text('TAX INVOICE', 350, 52, { align: 'right', width: 190 });

        doc.fillColor('#cbd5e1')
          .fontSize(10)
          .font('Helvetica')
          .text(`Invoice No: ${data.billNumber}`, 350, 78, { align: 'right', width: 190 });

        // ── 2. METADATA SECTION ───────────────────────────────────
        let y = 125;

        // Left column: Bill To (School)
        doc.fillColor('#64748b')
          .fontSize(10)
          .font('Helvetica-Bold')
          .text('BILLED TO (SCHOOL / INSTITUTION):', 50, y);

        y += 18;
        doc.fillColor('#0f172a')
          .fontSize(14)
          .font('Helvetica-Bold')
          .text(data.schoolName, 50, y);

        y += 18;
        doc.fillColor('#475569')
          .fontSize(10)
          .font('Helvetica')
          .text(`Institution Code: ${data.schoolCode}`, 50, y);

        if (data.schoolEmail) {
          y += 14;
          doc.text(`Email: ${data.schoolEmail}`, 50, y);
        }
        if (data.schoolPhone) {
          y += 14;
          doc.text(`Contact: ${data.schoolPhone}`, 50, y);
        }
        if (data.schoolAddress) {
          y += 14;
          doc.text(`Address: ${data.schoolAddress}`, 50, y);
        }

        // Right column: Invoice Details
        let rightY = 125;
        doc.fillColor('#64748b')
          .fontSize(10)
          .font('Helvetica-Bold')
          .text('INVOICE DETAILS:', 340, rightY);

        rightY += 18;
        doc.fillColor('#475569').fontSize(10).font('Helvetica');
        doc.text(`Invoice Date: ${formattedDate}`, 340, rightY);
        rightY += 14;
        doc.font('Helvetica-Bold').text(`Billing Period: ${billingPeriodStr}`, 340, rightY);
        rightY += 14;
        doc.font('Helvetica').text(`Invoice Status: ${data.status}`, 340, rightY);
        if (data.createdByName) {
          rightY += 14;
          doc.text(`Generated By: ${data.createdByName}`, 340, rightY);
        }
        if (data.approvedByName) {
          rightY += 14;
          doc.text(`Approved By: ${data.approvedByName}`, 340, rightY);
        }

        y = Math.max(y, rightY) + 25;

        // ── 3. TABLE HEADER ───────────────────────────────────────
        doc.rect(40, y, 515, 26).fill('#f1f5f9');
        doc.fillColor('#334155')
          .fontSize(9)
          .font('Helvetica-Bold')
          .text('SR', 50, y + 8)
          .text('DESCRIPTION / PARTICULARS', 80, y + 8)
          .text('STUDENTS', 280, y + 8, { align: 'right', width: 60 })
          .text('PRICE/STUDENT', 355, y + 8, { align: 'right', width: 90 })
          .text('TOTAL (INR)', 450, y + 8, { align: 'right', width: 90 });

        y += 26;

        // ── 4. LINE ITEMS ─────────────────────────────────────────
        const rowHeight = 45;
        doc.rect(40, y, 515, rowHeight).stroke('#e2e8f0');

        doc.fillColor('#0f172a')
          .fontSize(9)
          .font('Helvetica')
          .text('1', 50, y + 14)
          .text(
            data.description || `Platform Assessment Subscription (${billingPeriodStr})`,
            80,
            y + 14,
            { width: 190 },
          );

        doc.text(
          studentCount > 0 ? studentCount.toLocaleString('en-IN') : '—',
          280,
          y + 14,
          { align: 'right', width: 60 },
        );

        doc.text(
          pricePerStudent > 0 ? `₹${pricePerStudent.toLocaleString('en-IN')}` : '—',
          355,
          y + 14,
          { align: 'right', width: 90 },
        );

        doc.font('Helvetica-Bold').text(
          `₹${data.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
          450,
          y + 14,
          { align: 'right', width: 90 },
        );

        y += rowHeight;

        // ── 5. TOTALS BREAKDOWN ───────────────────────────────────
        y += 15;
        const subtotalY = y;
        doc.fillColor('#475569')
          .fontSize(10)
          .font('Helvetica')
          .text('Subtotal:', 340, subtotalY)
          .text(`₹${data.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, subtotalY, { align: 'right', width: 110 });

        const taxY = subtotalY + 18;
        doc.text('Tax / Cess (0%):', 340, taxY)
          .text(`₹${data.tax.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, taxY, { align: 'right', width: 110 });

        const totalY = taxY + 22;
        doc.rect(330, totalY - 4, 225, 30).fill('#f8fafc').stroke('#cbd5e1');
        doc.fillColor('#0f172a')
          .fontSize(12)
          .font('Helvetica-Bold')
          .text('Total Amount:', 340, totalY + 4)
          .text(`₹${data.totalAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, totalY + 4, { align: 'right', width: 110 });

        y = totalY + 50;

        // ── 6. PAYMENT / TERMS & FOOTER ───────────────────────────
        doc.rect(40, y, 515, 60).fill('#f8fafc').stroke('#e2e8f0');
        doc.fillColor('#475569')
          .fontSize(9)
          .font('Helvetica-Bold')
          .text('Payment Terms & Billing Summary:', 55, y + 10);

        doc.font('Helvetica')
          .text('1. Invoice calculated based on verified active student count for the billing period.', 55, y + 23)
          .text('2. Please quote Invoice Number on bank transfers and platform communications.', 55, y + 34)
          .text('3. This is a computer-generated institutional invoice and requires no physical signature.', 55, y + 45);

        // Footer at bottom
        doc.fillColor('#94a3b8')
          .fontSize(8)
          .text(
            'Brainros Exam Management Platform • Confirmed Institutional Bill • All Rights Reserved.',
            40,
            780,
            { align: 'center', width: 515 },
          );

        doc.end();
      } catch (err) {
        this.logger.error(`Error compiling bill PDF: ${(err as any).message}`);
        reject(err);
      }
    });
  }
}

