export enum QuestionTypeEnum {
  SINGLE_CORRECT = 'SINGLE_CORRECT',
  MULTIPLE_CORRECT = 'MULTIPLE_CORRECT',
  NUMERICAL = 'NUMERICAL',
  ASSERTION_REASON = 'ASSERTION_REASON',
  MATCH_FOLLOWING = 'MATCH_FOLLOWING',
  CASE_BASED = 'CASE_BASED',
}
